# **Import Library**

In [ ]:
import pandas as pd
import numpy as np

from google.colab import files

pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)

# **Upload Dataset dari Desktop**

In [ ]:
uploaded = files.upload()

Saving RAW_2026_03_01_Bali_Data_Tripadvisor+GoogleReview.xlsx to RAW_2026_03_01_Bali_Data_Tripadvisor+GoogleReview.xlsx

# **Load Dataset**

In [ ]:
file_name = list(uploaded.keys())[0]

df = pd.read_excel(file_name)

print("Dataset berhasil dimuat.")

Dataset berhasil dimuat.

# **Informasi Dataset**

In [ ]:
print("="*60)
print("INFORMASI DATASET")
print("="*60)

print(f"Jumlah Data   : {df.shape[0]:,}")
print(f"Jumlah Atribut: {df.shape[1]}")

print("\nNama Atribut:")
display(pd.DataFrame(df.columns, columns=["Atribut"]))

print("\nTipe Data:")
display(df.dtypes.reset_index().rename(columns={
    "index":"Atribut",
    0:"Tipe Data"
}))

============================================================
INFORMASI DATASET
============================================================
Jumlah Data   : 22,128
Jumlah Atribut: 13

Nama Atribut:

        Atribut
0    place_name
1      place_id
2       user_id
3        rating
4       address
5          city
6   postal_code
7      latitude
8     longitude
9      language
10  review_text
11  review_date
12       source

Tipe Data:

        Atribut       Tipe Data
0    place_name          object
1      place_id          object
2       user_id          object
3        rating           int64
4       address          object
5          city          object
6   postal_code         float64
7      latitude         float64
8     longitude         float64
9      language          object
10  review_text          object
11  review_date  datetime64[ns]
12       source          object

In [ ]:
print("5 Data Pertama")

display(df.head())

5 Data Pertama

,place_name,place_id,user_id,rating,address,city,postal_code,latitude,longitude,language,review_text,review_date,source
0,Kebon Vintage Cars,ChIJ2XkpGghA0i0RI_bG3blIIfw,106930109531231364164,5,"Jl. Tegal Harum No.13, Biaung, Kec. Denpasar Tim., Kota Denpasar, Bali, Indonesia",Denpasar City,NaN,-8.646858,115.270905,en,"Рекомендую всем, фанатам, детям и женщинам будет интересно! Внутри кафе и магазинчик, машин 150-200.",2026-02-23,Google Review
1,Kebon Vintage Cars,ChIJ2XkpGghA0i0RI_bG3blIIfw,114125858000695161899,5,"Jl. Tegal Harum No.13, Biaung, Kec. Denpasar Tim., Kota Denpasar, Bali, Indonesia",Denpasar City,NaN,-8.646858,115.270905,en,"Had a wonderful time at Kebon Vintage Cars, looking around at the collection was really interesting! The guide Mirah was also very nice and welcoming, explaining to me the history of the owner and his collection, while also showing a lot of care and concern. Highly recommend!",2026-02-23,Google Review
2,Kebon Vintage Cars,ChIJ2XkpGghA0i0RI_bG3blIIfw,116066024977580496440,5,"Jl. Tegal Harum No.13, Biaung, Kec. Denpasar Tim., Kota Denpasar, Bali, Indonesia",Denpasar City,NaN,-8.646858,115.270905,en,NaN,2026-02-22,Google Review
3,Kebon Vintage Cars,ChIJ2XkpGghA0i0RI_bG3blIIfw,106267854069918998617,5,"Jl. Tegal Harum No.13, Biaung, Kec. Denpasar Tim., Kota Denpasar, Bali, Indonesia",Denpasar City,NaN,-8.646858,115.270905,en,"Was wonderful experience to visite kebon vintage,with amazing staff ,was had great day with Mira She was help do photo shoot,video with her professional skills,,,can’t wait to visit again when I come back to bali",2026-02-21,Google Review
4,Kebon Vintage Cars,ChIJ2XkpGghA0i0RI_bG3blIIfw,116285786349621470036,5,"Jl. Tegal Harum No.13, Biaung, Kec. Denpasar Tim., Kota Denpasar, Bali, Indonesia",Denpasar City,NaN,-8.646858,115.270905,en,Great selection of cars from private collection. You even get a guide who is very knowledgeable so easy to chat about the various cars and other vintage memorabilia.,2026-02-21,Google Review

# **Identifikasi Missing Value**

In [ ]:
missing = pd.DataFrame({
    "Atribut": df.columns,
    "Jumlah Missing Value": df.isnull().sum().values,
    "Persentase (%)": (
        df.isnull().sum().values /
        len(df) * 100
    ).round(2)
})

print("="*60)
print("MISSING VALUE")
print("="*60)

display(missing)

============================================================
MISSING VALUE
============================================================

        Atribut  Jumlah Missing Value  Persentase (%)
0    place_name                     0            0.00
1      place_id                     0            0.00
2       user_id                     8            0.04
3        rating                     0            0.00
4       address                     0            0.00
5          city                  2513           11.36
6   postal_code                  4229           19.11
7      latitude                    72            0.33
8     longitude                    72            0.33
9      language                     0            0.00
10  review_text                  6462           29.20
11  review_date                     0            0.00
12       source                     0            0.00

# **Identifikasi Duplikasi Baris**

In [ ]:
duplicate_rows = df.duplicated().sum()

print("="*60)
print("DUPLIKASI BARIS")
print("="*60)

print(f"Jumlah duplikasi baris: {duplicate_rows}")

============================================================
DUPLIKASI BARIS
============================================================
Jumlah duplikasi baris: 192

# **Identifikasi Place Name dengan Banyak Place ID**

In [ ]:
multiple_place_id = (
    df.groupby("place_name")["place_id"]
      .nunique()
      .reset_index(name="Jumlah Place ID")
)

multiple_place_id = multiple_place_id[
    multiple_place_id["Jumlah Place ID"] > 1
]

print("="*60)
print("PLACE NAME DENGAN LEBIH DARI SATU PLACE ID")
print("="*60)

print(f"Jumlah Place Name: {len(multiple_place_id)}")

display(multiple_place_id.head(20))

============================================================
PLACE NAME DENGAN LEBIH DARI SATU PLACE ID
============================================================
Jumlah Place Name: 40

                                  place_name  Jumlah Place ID
4             Agung Rai Museum of Art (ARMA)                4
12                         Angel's Billabong                2
19        BMW Telaga Waja River Bali Rafting                6
21                     Bajra Sandhi Monument                2
23                            Bali Bird Park                4
29                            Bali Wake Park                5
34              Banyu Wana Amertha Waterfall                2
36                        Barong Tanah Kilap                2
47                          Bias Tugel Beach                2
48                         Big Garden Corner                2
62              CitraLand Waterpark Denpasar                2
66   Deluang Sari Turtle Conservation Center                2
70                             Devil's Tears                2
74                        Duta Orchid Garden                2
79               Gala-Gala Underground House                2
110                    Kanto Lampo Waterfall                2
115              Kertalangu Cultural Village                2
130                      Leke Leke Waterfall                2
131                         Lempuyang Temple                2
133                       Maha Gangga Valley                2

# **Identifikasi User-Item Ganda**

In [ ]:
duplicate_user_item = (
    df.groupby(["user_id","place_id"])
      .size()
      .reset_index(name="Jumlah")
)

duplicate_user_item = duplicate_user_item[
    duplicate_user_item["Jumlah"] > 1
]

print("="*60)
print("USER-ITEM DENGAN LEBIH DARI SATU RATING")
print("="*60)

print(f"Jumlah pasangan user-item: {len(duplicate_user_item)}")

display(duplicate_user_item.head(20))

============================================================
USER-ITEM DENGAN LEBIH DARI SATU RATING
============================================================
Jumlah pasangan user-item: 228

                               user_id                     place_id  Jumlah
190   06D82195179214017A9315FA91464B65                      9705661       2
233   085D1D817F7DD16CCF71246B18F48514                      9705661       2
409   0E830A97EAF038183048D02ACA9BCF1B                      9705661       2
530              100063624851557714736  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
561              100089951711835126913  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
760              100317371042644259029  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
856              100438894012343923224  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
922              100504030479215468951  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
942              100526307991497429973  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
1092             100712010634742521141  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
1306             100961068953929959332  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
1405             101089725016278994516  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
1679             101424782794046001574  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
1692             101440399656610411184  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
1853             101623704168994302930  ChIJ19RoPhhiby4RXg2T181MANY       2
2166             102009475934942190302  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
2280             102148870723531929215  ChIJ19RoPhhiby4RXg2T181MANY       2
2640             102600104951863298422  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
2743             102716598067614530976  ChIJpR8_7qCJ0S0RHlO03mW65YY       2
2759             102732410024102249519  ChIJpR8_7qCJ0S0RHlO03mW65YY       2

# **Ringkasan Kondisi Awal Dataset**

In [ ]:
print("="*70)
print("RINGKASAN KONDISI AWAL DATASET")
print("="*70)

print(f"Jumlah Data                     : {len(df):,}")
print(f"Jumlah Missing Value            : {df.isnull().sum().sum():,}")
print(f"Jumlah Duplikasi Baris          : {duplicate_rows:,}")
print(f"Place Name > 1 Place ID         : {len(multiple_place_id):,}")
print(f"User-Item > 1 Rating            : {len(duplicate_user_item):,}")

======================================================================
RINGKASAN KONDISI AWAL DATASET
======================================================================
Jumlah Data                     : 22,128
Jumlah Missing Value            : 13,356
Jumlah Duplikasi Baris          : 192
Place Name > 1 Place ID         : 40
User-Item > 1 Rating            : 228

# **Seleksi Atribut**

In [ ]:
required_columns = [
    "user_id",
    "place_id",
    "rating",
    "place_name",
    "review_date",
    "source"
]

df_clean = df[required_columns].copy()

print("="*60)
print("SELEKSI ATRIBUT")
print("="*60)

print(f"Jumlah atribut sebelum seleksi : {df.shape[1]}")
print(f"Jumlah atribut sesudah seleksi : {df_clean.shape[1]}")

display(df_clean.head())

============================================================
SELEKSI ATRIBUT
============================================================
Jumlah atribut sebelum seleksi : 13
Jumlah atribut sesudah seleksi : 6

,user_id,place_id,rating,place_name,review_date,source
0,106930109531231364164,ChIJ2XkpGghA0i0RI_bG3blIIfw,5,Kebon Vintage Cars,2026-02-23,Google Review
1,114125858000695161899,ChIJ2XkpGghA0i0RI_bG3blIIfw,5,Kebon Vintage Cars,2026-02-23,Google Review
2,116066024977580496440,ChIJ2XkpGghA0i0RI_bG3blIIfw,5,Kebon Vintage Cars,2026-02-22,Google Review
3,106267854069918998617,ChIJ2XkpGghA0i0RI_bG3blIIfw,5,Kebon Vintage Cars,2026-02-21,Google Review
4,116285786349621470036,ChIJ2XkpGghA0i0RI_bG3blIIfw,5,Kebon Vintage Cars,2026-02-21,Google Review

# **Missing Value pada 6 atribut utama**

In [ ]:
missing_required = pd.DataFrame({
    "Atribut": df_clean.columns,
    "Jumlah Missing Value": df_clean.isnull().sum().values,
    "Persentase (%)": (
        df_clean.isnull().sum().values /
        len(df_clean) * 100
    ).round(2)
})

print("="*60)
print("MISSING VALUE PADA ATRIBUT UTAMA")
print("="*60)

display(missing_required)

============================================================
MISSING VALUE PADA ATRIBUT UTAMA
============================================================

       Atribut  Jumlah Missing Value  Persentase (%)
0      user_id                     8            0.04
1     place_id                     0            0.00
2       rating                     0            0.00
3   place_name                     0            0.00
4  review_date                     0            0.00
5       source                     0            0.00

# **Menghapus Missing Value**

In [ ]:
jumlah_sebelum = len(df_clean)

df_clean = df_clean.dropna(
    subset=required_columns
).reset_index(drop=True)

jumlah_sesudah = len(df_clean)

print("="*60)
print("PENGHAPUSAN MISSING VALUE")
print("="*60)

print(f"Jumlah data sebelum : {jumlah_sebelum:,}")
print(f"Jumlah data sesudah : {jumlah_sesudah:,}")
print(f"Jumlah data dihapus : {jumlah_sebelum-jumlah_sesudah:,}")

============================================================
PENGHAPUSAN MISSING VALUE
============================================================
Jumlah data sebelum : 22,128
Jumlah data sesudah : 22,120
Jumlah data dihapus : 8

# **Normalisasi place_id**

In [ ]:
df_clean["review_date"] = pd.to_datetime(df_clean["review_date"])

canonical_place = (
    df_clean
    .sort_values("review_date")
    .groupby("place_name")
    .tail(1)[["place_name", "place_id"]]
    .rename(columns={"place_id":"canonical_place_id"})
)

display(canonical_place.head())

,place_name,canonical_place_id
20042,Jembong Waterfall,9718627
16625,Taman Narmada Bali Raja,19757881
20041,Penimbangan Beach,17853448
9289,Tourist Information Centre Desa Wisata Blimbingsari,ChIJKTzCu51d0S0R45V7bBGJRwc
11319,KANTOR PERBEKEL DESA KINTAMANI,ChIJUbVDErX10S0Rbp3R3ywxFXg

# **Membuat Mapping Place ID**

In [ ]:
mapping = (
    df_clean[
        ["place_name","place_id"]
    ]
    .drop_duplicates()
    .merge(
        canonical_place,
        on="place_name",
        how="left"
    )
)

display(mapping.head(20))

,place_name,place_id,canonical_place_id
0,Kebon Vintage Cars,ChIJ2XkpGghA0i0RI_bG3blIIfw,ChIJ2XkpGghA0i0RI_bG3blIIfw
1,Fingerprint Painting Museum,ChIJdyQo2WNA0i0RE6o_3uTsTSE,ChIJdyQo2WNA0i0RE6o_3uTsTSE
2,Makam Keramat Ratu Ayu Siti Khodijah Pemecutan,ChIJHdKhzbxA0i0R9FHKpPCWtrU,ChIJHdKhzbxA0i0R9FHKpPCWtrU
3,Sanur Beach,ChIJs1vLBTlA0i0RQbKxRDweyHE,ChIJs1vLBTlA0i0RQbKxRDweyHE
4,Badung Market,ChIJEcsIC6JA0i0RXn4iHsIOYMA,ChIJEcsIC6JA0i0RXn4iHsIOYMA
5,Museum Le Mayeur,ChIJq-2TrzlA0i0RwvUDjrMII7w,ChIJq-2TrzlA0i0RwvUDjrMII7w
6,Pura Agung Petilan,ChIJjbBXpYg_0i0RohXOpEShubU,ChIJjbBXpYg_0i0RohXOpEShubU
7,Taman Wisata Tukad Bindu,ChIJu0Dbm3g_0i0ReErLR0BFjww,ChIJu0Dbm3g_0i0ReErLR0BFjww
8,Agung Jagatnatha Temple,ChIJky6y2ZtA0i0RMPn08WYBq9E,ChIJky6y2ZtA0i0RMPn08WYBq9E
9,Pasar Sindu,ChIJVYamARlDBAURKBC_PxX5Azw,ChIJVYamARlDBAURKBC_PxX5Azw
10,The Blooms,ChIJpR8_7qCJ0S0RHlO03mW65YY,ChIJpR8_7qCJ0S0RHlO03mW65YY
11,Sakenan Temple,ChIJM7nrKSM_0i0RIfYXvNa8uFo,ChIJM7nrKSM_0i0RIfYXvNa8uFo
12,Museum Subak,ChIJz1WG_po_0i0R9WLS_bDbjv8,ChIJz1WG_po_0i0R9WLS_bDbjv8
13,Tanah Lot,ChIJq95xT4I30i0RaU3j93Diq8o,379340
14,Air Panas Angseri,ChIJ_____8OJ0S0RzYLkKOcHW_M,ChIJ_____8OJ0S0RzYLkKOcHW_M
15,Hot Spring Penatahan Kaja,ChIJLxmtWMcl0i0RWl489did7JQ,ChIJLxmtWMcl0i0RWl489did7JQ
16,Puri Agung Kerambitan,ChIJzbfwpmtXBAUR1jYgQhksDMM,ChIJzbfwpmtXBAUR1jYgQhksDMM
17,Rumah Gemuk Bali,ChIJ31YjHteJ0S0RwrmFgkQ4Rys,ChIJ31YjHteJ0S0RwrmFgkQ4Rys
18,Bali Butterfly Park Tabanan,ChIJMaOrTtM60i0RRirULm_EL5s,ChIJMaOrTtM60i0RRirULm_EL5s
19,Bali Wake Park,ChIJq6HQF2dB0i0RG4g6CYqaKd0,ChIJq6HQF2dB0i0RG4g6CYqaKd0

# **Mengganti Seluruh place_id**

In [ ]:
df_clean = df_clean.merge(
    canonical_place,
    on="place_name",
    how="left"
)

df_clean["place_id"] = df_clean["canonical_place_id"]

df_clean.drop(
    columns="canonical_place_id",
    inplace=True
)

print("="*60)
print("NORMALISASI PLACE ID SELESAI")
print("="*60)

============================================================
NORMALISASI PLACE ID SELESAI
============================================================

# **Menampilkan Jumlah place_id yang Dinormalisasi**

In [ ]:
jumlah_normalisasi = (
    mapping["place_id"] != mapping["canonical_place_id"]
).sum()

print("="*60)
print("HASIL NORMALISASI PLACE ID")
print("="*60)

print(f"Jumlah place_id yang dinormalisasi : {jumlah_normalisasi:,}")

============================================================
HASIL NORMALISASI PLACE ID
============================================================
Jumlah place_id yang dinormalisasi : 53

# **Menghapus Duplikasi User-Item**

In [ ]:
jumlah_sebelum = len(df_clean)

df_clean = (
    df_clean
    .sort_values(
        by=["review_date","rating"],
        ascending=[False,False]
    )
    .drop_duplicates(
        subset=["user_id","place_id"],
        keep="first"
    )
    .reset_index(drop=True)
)

jumlah_sesudah = len(df_clean)

print("="*60)
print("PENGHAPUSAN DUPLIKASI USER-ITEM")
print("="*60)

print(f"Jumlah data sebelum : {jumlah_sebelum:,}")
print(f"Jumlah data sesudah : {jumlah_sesudah:,}")
print(f"Jumlah data dihapus : {jumlah_sebelum-jumlah_sesudah:,}")

============================================================
PENGHAPUSAN DUPLIKASI USER-ITEM
============================================================
Jumlah data sebelum : 22,120
Jumlah data sesudah : 21,886
Jumlah data dihapus : 234

# **Menghapus Duplikasi Baris**

In [ ]:
jumlah_sebelum = len(df_clean)

df_clean = (
    df_clean
    .drop_duplicates()
    .reset_index(drop=True)
)

jumlah_sesudah = len(df_clean)

print("="*60)
print("PENGHAPUSAN DUPLIKASI BARIS")
print("="*60)

print(f"Jumlah data sebelum : {jumlah_sebelum:,}")
print(f"Jumlah data sesudah : {jumlah_sesudah:,}")
print(f"Jumlah data dihapus : {jumlah_sebelum-jumlah_sesudah:,}")

============================================================
PENGHAPUSAN DUPLIKASI BARIS
============================================================
Jumlah data sebelum : 21,886
Jumlah data sesudah : 21,886
Jumlah data dihapus : 0

# **Validasi Hasil Praproses**

In [ ]:
print("="*70)
print("VALIDASI HASIL PRAPROSES")
print("="*70)

print(f"Jumlah Missing Value : {df_clean.isnull().sum().sum():,}")

print(f"Duplikasi Baris      : {df_clean.duplicated().sum():,}")

cek_user_item = (
    df_clean
    .groupby(["user_id","place_id"])
    .size()
    .gt(1)
    .sum()
)

print(f"User-Item Ganda      : {cek_user_item:,}")

cek_place = (
    df_clean
    .groupby("place_name")["place_id"]
    .nunique()
    .gt(1)
    .sum()
)

print(f"Place Name >1 ID     : {cek_place:,}")

print(f"Jumlah Data Akhir    : {len(df_clean):,}")

======================================================================
VALIDASI HASIL PRAPROSES
======================================================================
Jumlah Missing Value : 0
Duplikasi Baris      : 0
User-Item Ganda      : 0
Place Name >1 ID     : 0
Jumlah Data Akhir    : 21,886

In [ ]:
output_file = "2026_07_17_Praproses_Data.xlsx"

df_clean.to_excel(
    output_file,
    index=False
)

print("="*60)
print("DATASET BERHASIL DISIMPAN")
print("="*60)

print(f"Nama File : {output_file}")

============================================================
DATASET BERHASIL DISIMPAN
============================================================
Nama File : 2026_07_17_Praproses_Data.xlsx

In [ ]:
cek_place = (
    df_clean
    .groupby("place_name")["place_id"]
    .nunique()
    .reset_index(name="Jumlah")
)

cek_place = cek_place[
    cek_place["Jumlah"] > 1
]

print(len(cek_place))

display(cek_place.head(20))

0

Empty DataFrame
Columns: [place_name, Jumlah]
Index: []

In [ ]:
display(mapping.head(20))

,place_name,place_id,canonical_place_id
0,Kebon Vintage Cars,ChIJ2XkpGghA0i0RI_bG3blIIfw,ChIJ2XkpGghA0i0RI_bG3blIIfw
1,Fingerprint Painting Museum,ChIJdyQo2WNA0i0RE6o_3uTsTSE,ChIJdyQo2WNA0i0RE6o_3uTsTSE
2,Makam Keramat Ratu Ayu Siti Khodijah Pemecutan,ChIJHdKhzbxA0i0R9FHKpPCWtrU,ChIJHdKhzbxA0i0R9FHKpPCWtrU
3,Sanur Beach,ChIJs1vLBTlA0i0RQbKxRDweyHE,ChIJs1vLBTlA0i0RQbKxRDweyHE
4,Badung Market,ChIJEcsIC6JA0i0RXn4iHsIOYMA,ChIJEcsIC6JA0i0RXn4iHsIOYMA
5,Museum Le Mayeur,ChIJq-2TrzlA0i0RwvUDjrMII7w,ChIJq-2TrzlA0i0RwvUDjrMII7w
6,Pura Agung Petilan,ChIJjbBXpYg_0i0RohXOpEShubU,ChIJjbBXpYg_0i0RohXOpEShubU
7,Taman Wisata Tukad Bindu,ChIJu0Dbm3g_0i0ReErLR0BFjww,ChIJu0Dbm3g_0i0ReErLR0BFjww
8,Agung Jagatnatha Temple,ChIJky6y2ZtA0i0RMPn08WYBq9E,ChIJky6y2ZtA0i0RMPn08WYBq9E
9,Pasar Sindu,ChIJVYamARlDBAURKBC_PxX5Azw,ChIJVYamARlDBAURKBC_PxX5Azw
10,The Blooms,ChIJpR8_7qCJ0S0RHlO03mW65YY,ChIJpR8_7qCJ0S0RHlO03mW65YY
11,Sakenan Temple,ChIJM7nrKSM_0i0RIfYXvNa8uFo,ChIJM7nrKSM_0i0RIfYXvNa8uFo
12,Museum Subak,ChIJz1WG_po_0i0R9WLS_bDbjv8,ChIJz1WG_po_0i0R9WLS_bDbjv8
13,Tanah Lot,ChIJq95xT4I30i0RaU3j93Diq8o,379340
14,Air Panas Angseri,ChIJ_____8OJ0S0RzYLkKOcHW_M,ChIJ_____8OJ0S0RzYLkKOcHW_M
15,Hot Spring Penatahan Kaja,ChIJLxmtWMcl0i0RWl489did7JQ,ChIJLxmtWMcl0i0RWl489did7JQ
16,Puri Agung Kerambitan,ChIJzbfwpmtXBAUR1jYgQhksDMM,ChIJzbfwpmtXBAUR1jYgQhksDMM
17,Rumah Gemuk Bali,ChIJ31YjHteJ0S0RwrmFgkQ4Rys,ChIJ31YjHteJ0S0RwrmFgkQ4Rys
18,Bali Butterfly Park Tabanan,ChIJMaOrTtM60i0RRirULm_EL5s,ChIJMaOrTtM60i0RRirULm_EL5s
19,Bali Wake Park,ChIJq6HQF2dB0i0RG4g6CYqaKd0,ChIJq6HQF2dB0i0RG4g6CYqaKd0